.\" Copyright (c) 2012 Microsoft Corp.
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.Dd September 10, 2013
.Dt HYPER-V 4
.Os
.Sh NAME
.Nm hyperv-ic
.Nd Hyper-V Integration Components
.Sh SYNOPSIS
The \fBhyperv-ic\fP provision a collection of kernel mode drivers and
services that enhance FreeBSD guest experience on Hyper-V. 

.Sh DESCRIPTION
The Hyper-V Integration Components include drivers and services that improve
functionality and performance of a FreeBSD guest operating system
running on Hyper-V. As of this writing, the \fBhyperv-ic\fP ports package
installs the following binaries:

a) hv_vmbus.ko - This is a loadable kernel module that provides a high 
performance communication interface between the FreeBSD guest partition 
and the Hyper-V root partition running Windows Server software. This module
is located under /boot/kernel/.

b) hv_storvsc.ko - This is a loadable kernel module that
provides FreeBSD guests with optimized access to physical storage devices.
This module is located under /boot/kernel/.

c) hv_netvsc.ko - This is a loadable kernel module that provides FreeBSD 
guests with optimized access to the physical network card.
This module is located under /boot/kernel/.

d) hv_utils.ko - This is a loadable kernel module that provides FreeBSD 
guests with timekeeping, heartbeat, console shutdown and key-value pair 
functionality. This module is located under /boot/kernel/.

e) hv_ata_pci_disengage.ko - This is a loadable kernel module that disables 
the FreeBSD native ATA driver in order to avoid conflicts with the hv_storvsc
driver. This module is located under /boot/kernel/.

f) hv_kvp_daemon - This is a user mode daemon that communicates with the hv_utils
driver to manage user configurable metadata in the form of key value pairs. 
This daemon also allows the system administrator to read and set IP 
addresses assigned to a FreeBSD guest. The daemon utilizes the following 
collection of scripts stored under /usr/local/hyperv/scripts:
.br
hv_get_dhcp_info 
.br
hv_get_dns_info 
.br
hv_set_ifconfig

The daemon is located under /usr/sbin/. The corresponding daemon script named
hv_kvpd is present under /etc/rc.d/.
.Sh PRE-REQUISITE
Before you install \fBhyperv-ic\fP ports, please ensure that you have added
disk labels or UUIDs to all devices listed in fstab.
.Sh SEE ALSO
.Xr hv_vmbus 4 ,
.Xr hv_utils 4 ,
.Xr hv_netvsc 4 ,
.Xr hv_storvsc 4 ,
.Xr hv_ata_pci_disengage 4 ,
.Xr hv_kvp_daemon 8
.Sh HISTORY
Support for \fBhyperv-ic\fP ports was first released in September 2013. The ports were developed through a joint effort between Citrix Inc., Microsoft Corp. and Network Appliance Inc..
.Sh AUTHORS
.An -nosplit
.Fx
support for \fBhyperv-ic\fP was first added by
.An Microsoft BSD Integration Services Team Aq bsdic@microsoft.com .
