# $FreeBSD hyperv-ic Makefile  $

.include <bsd.own.mk>

MAN1=	hyperv-ic.1

MAN4=	hv_ata_pci_disengage.4 \
	hv_kvp.4 \
	hv_netvsc.4 \
	hv_storvsc.4 \
	hv_utils.4 \
	hv_vmbus.4

.include <bsd.prog.mk>
