#!/bin/sh
#
# make install or pkg_add script
# Checks labels/gptids for roots and swap partitions
# adds hyperv labels in loader.conf 
#


#Check poudriere workdirs
POD_WRK_HOME=/wrkdirs
if [ ! -d ${POD_WRK_HOME} ]; then
      POD_WRK_HOME=/
fi

WRKDIRS=${POD_WRK_HOME}$(pwd |awk '{print $1}')/work/stage
if [ ! -d ${WRKDIRS} ]; then
   WRKDIRS=/
fi

rel=`uname -r`
ver=${rel%-*}
major=${ver%.*}
minor=${ver#*.}

if [ "$2" = "PRE-INSTALL" ]; then
    echo "===> Pre-install Check"

    #rootfs check
    root_flag=$(mount | awk '/ on \/ / { print $1 }' | cut -d / -f3-)
    if [ "$root_flag" != "" ]; then
        fs_test=$(glabel status | awk '{print $1}' | grep $root_flag)
        if [ "$fs_test" == "" ]; then
            echo " xxx rootfs Label/gptid missing in fstab"  
        fi
    else 
        echo " xxx rootfs Label/gptid missing in fstab"
    fi

    #swap check
    [ -f /etc/fstab ] && swap_flag=$(grep swap /etc/fstab | awk '{print $1}' | cut -d / -f3-)
    if [ "$swap_flag" != "" ]; then
        sw_test=$(glabel status | awk '{print $1}' | grep $swap_flag)
    fi
    if [ "$sw_test" == "" ]; then
         echo " xxx swap Label/gptid missing in fstab"  
    else   
        echo " xxx swap Label/gptid missing in fstab "
    fi

    if [ "$fs_test" != "" -a  "$sw_test" != "" ]; then
        echo "===> Labels/gptids Found"
        echo "===> Hyper-V BIS Installation Continues"
    else
        if [ $major -lt 10 ]; then
           echo "version is $version"
           echo "===> Labels/gptids Not found"
           echo "===> Hyper-V BIS Installation Aborted"
           echo "===> Refer to Disk UUID section in README document"
           echo "===> Please refer the Prerequisites page and complete all steps" 
           echo "http://technet.microsoft.com/en-us/library/0c66f1c8-2606-43a3-b4cc-166acaaf2d2a#BKMK_UUID " 
           exit 1 
        fi
    fi
    
    kvp_dir="/var/db/hyperv/"
    kvp_dir_scripts="/var/db/hyperv/scripts"
    if [ -d $kvp_dir ]; then
        if [ -d $kvp_dir_scripts ]; then
            echo " KVP Directories present "
        else
            mkdir /var/db/hyperv/scripts
        fi
    else
        mkdir /var/db/hyperv
        mkdir /var/db/hyperv/scripts
    fi
fi
exit 0
