# $FreeBSD hyperv-ic Makefile  $

.include <bsd.own.mk>

FILES= hv_get_dhcp_info hv_get_dns_info hv_set_ifconfig

FILESDIR=       /usr/local/hyperv/scripts
FILESMODE=      755

.include <bsd.prog.mk>
