#!/bin/sh
#
# make deinstall or pkd_delete script 
# cleans the hyperv labels
#

if [ "$2" = "DEINSTALL" ]; then
   test="/boot/loader.conf"

   if [ -f $test ]; then
   echo "===> File $test exists"
   echo  "Removing Hyper-v BIS drivers labels "
   # Deleting Hyper-v BIS driver names
   sed -i "" '/Loader labels for Hyper-V driver/d' /boot/loader.conf
   sed -i "" '/hv_vmbus_load/d' /boot/loader.conf
   sed -i "" '/hv_utils_load/d' /boot/loader.conf
   sed -i "" '/hv_storvsc_load/d' /boot/loader.conf
   sed -i "" '/hv_netvsc_load/d' /boot/loader.conf
   sed -i "" '/hv_ata_pci_disengage_load/d' /boot/loader.conf
   else 
   echo "===> File $test not found"
   fi

echo "===> Removing kvp daemon label"
sed -i "" '/Labels for KVP daemon/d' /etc/rc.conf
sed -i "" '/hv_kvp_daemon_enable/d' /etc/rc.conf
# Remove rc.conf and loader.conf if null
rc_content=$(cat /etc/rc.conf |awk '{print $0}')
loader_content=$(cat /boot/loader.conf |awk '{print $0}')
if [ ${rc_content}="" ]; then
    rm /etc/rc.conf
   if [ -f /etc/rc.conf.bak ]; then
      rm /etc/rc.conf.bak
   fi
fi

if [ ${loader_content}="" ]; then
   rm /boot/loader.conf
   if [ -f /boot/loader.conf.bak ]; then
      rm /boot/loader.conf.bak
   fi
fi

fi
exit 0
