#!/bin/sh
#
# make install or pkg_add script
# Checks labels/gptids for roots and swap partitions
# adds hyperv labels in loader.conf 
#

#Check poudriere workdirs
POD_WRK_HOME=/wrkdirs
if [ -d ${POD_WRK_HOME} ]; then
   else
      POD_WRK_HOME=/
fi
WRKDIRS=${POD_WRK_HOME}$(pwd |awk '{print $1}')/work/stage

if [ "$2" = "PRE-INSTALL" ]; then
echo "===> Pre-install Check"

#rootfs check
root_flag=$(mount | awk '/ on \/ / { print $1 }' | cut -d / -f3-)
if [ "$root_flag" != "" ]; then
   fs_test=$(glabel status | awk '{print $1}' | grep $root_flag)
   if [ "$fs_test" == "" ]; then
      echo " xxx rootfs Label/gptid missing in fstab"  
   fi
else 
   echo " xxx rootfs Label/gptid missing in fstab"
fi
#swap check
swap_flag=$(grep swap /etc/fstab | awk '{print $1}' | cut -d / -f3-)
if [ "$swap_flag" != "" ]; then
   sw_test=$(glabel status | awk '{print $1}' | grep $swap_flag)
   if [ "$sw_test" == "" ]; then
      echo " xxx swap Label/gptid missing in fstab"  
   fi
else   
   echo " xxx swap Label/gptid missing in fstab "
fi

if [ "$fs_test" != "" -a  "$sw_test" != "" ]; then
   echo "===> Labels/gptids Found"
   echo "===> Hyper-V BIS Installation Continues"
else
   echo "===> Labels/gptids Not found"
   echo "===> Hyper-V BIS Installation Aborted"
   echo "===> Refer to Disk UUID section in README document"
   echo "===> Please refer the Prerequisites page and complete all steps" 
   echo "WWW: https://github.com/FreeBSDonHyper-V/Hyperv-Ports/wiki/Prerequisites " 
   exit -1 
fi
if [ -d ${WRKDIRS} ]; then
if [ -d ${WRKDIRS}"/usr" ]; then
   if [ -d ${WRKDIRS}"/usr/local" ]; then
   else
         mkdir ${WRKDIRS}/usr/local
   fi
else
      mkdir ${WRKDIRS}/usr
      mkdir ${WRKDIRS}/usr/local
fi


# KVP - Directories Check
echo "===> Checking KVP directories" 
kvp_dir="${WRKDIRS}/usr/local/hyperv/"
kvp_dir_scripts="${WRKDIRS}/usr/local/hyperv/scripts"

if [ -d $kvp_dir ]; then
   if [ -d $kvp_dir_scripts ]; then
      echo " ### KVP Directories present " 
   else 
      echo " ### Creating $kvp_dir_scripts directory "
      mkdir ${WRKDIRS}/usr/local/hyperv/scripts
   fi
else 
   echo " xxx KVP directories not found"
   echo " ### Creating KVP  directories "
   mkdir ${WRKDIRS}/usr/local/hyperv
   mkdir ${WRKDIRS}/usr/local/hyperv/scripts
fi

# ETC Directories Check

echo "===> Checking Daemon Install directories"
etc_dir="${WRKDIRS}/etc"
etc_rc_dir="${WRKDIRS}/etc/rc.d"

if [ -d $etc_dir ]; then
   if [ -d $etc_rc_dir ]; then
      echo " ### ETCRC directories present "
   else
      echo " ### Creating $etc_rc_dir directory "
      mkdir ${WRKDIRS}/etc/rc.d
   fi
else
   echo " xxx ETC directories not found"
   echo " ### Creating ETC directories "
   mkdir ${WRKDIRS}/etc
   mkdir ${WRKDIRS}/etc/rc.d
fi 

# DAEMONBIN Directories Check

echo "===> Checking Install Daemon directories"
sbin_dir="${WRKDIRS}/usr/sbin"

if [ -d $sbin_dir ]; then
   echo " ### SBIN Directories present"
else
   echo " xxx SBIN directories not found"
   echo " ### Creating SBIN directories "
   mkdir $sbin_dir 
fi 

# KERNEL Directories Check

echo "===> Checking Install Boot directories"
boot_dir="${WRKDIRS}/boot"
kernel_dir="${WRKDIRS}/boot/kernel"

if [ -d $boot_dir ]; then
   if [ -d $kernel_dir ]; then
      echo " ### KERNEL diretories present"
   else
      echo " ### Creating Kernel diretories "
      mkdir $kernel_dir
   fi
else 
   echo " xxx BOOT directories not found"
   echo " ### Creating BOOT direcories"
   mkdir $boot_dir 
   mkdir $kernel_dir 
fi

#Check Share directories
share_dir="${WRKDIRS}/usr/share"
if [ -d $share_dir ]; then
   echo " ### Share directories present "
else
   echo " ### Creating Share direcories "
   mkdir $share_dir
fi

#Check man directories
man_dir="$share_dir/man"
if [ -d $man_dir ]; then
   echo " ### Man directories present "
else
   mkdir $man_dir
fi

#Check subdir
man1_dir="$man_dir/man1"
man4_dir="$man_dir/man4"
man8_dir="$man_dir/man8"
if [ -d $man1_dir ]; then
   else
     mkdir $man1_dir
     mkdir $man4_dir
     mkdir $man8_dir
fi

else
# KVP - Directories Check
echo "===> Checking KVP directories" 
kvp_dir="/usr/local/hyperv/"
kvp_dir_scripts="/usr/local/hyperv/scripts"

if [ -d $kvp_dir ]; then
   if [ -d $kvp_dir_scripts ]; then
      echo " ### KVP Directories present " 
   else 
      echo " ### Creating $kvp_dir_scripts directory "
      mkdir /usr/local/hyperv/scripts
   fi
else 
   echo " xxx KVP directories not found"
   echo " ### Creating KVP  directories "
   mkdir /usr/local/hyperv
   mkdir /usr/local/hyperv/scripts
fi
fi
else if [ "$2" = "POST-INSTALL" ]; then
   test="/boot/loader.conf"
   if [ -d ${WRKDIRS} ]; then
      rm -f ${WRKDIRS}/boot/kernel/linker.hints 
   else 
      rm -f /boot/kernel/linker.hints
   fi
   if [ -f $test ]; then
      echo "===> File $test exists"
      echo "Adding for Hyper-v drivers"

      # Deleting Hyper-v BIS driver names
      sed -i".bak" '/Loader labels for Hyper-v BIS driver/d' /boot/loader.conf
      sed -i".bak" '/hv_vmbus_load/d' /boot/loader.conf
      sed -i".bak" '/hv_utils_load/d' /boot/loader.conf
      sed -i".bak" '/hv_storvsc_load/d' /boot/loader.conf
      sed -i".bak" '/hv_netvsc_load/d' /boot/loader.conf
      sed -i".bak" '/hv_ata_pci_disengage_load/d' /boot/loader.conf

      #Hyper-v driver names
      echo  "# Loader labels for Hyper-v BIS drivers -do not modify" >> /boot/loader.conf
      echo  "hv_vmbus_load=\"YES\"" >> /boot/loader.conf
      echo  "hv_utils_load=\"YES\""  >> /boot/loader.conf
      echo  "hv_storvsc_load=\"YES\""  >> /boot/loader.conf
      echo  "hv_netvsc_load=\"YES\""  >> /boot/loader.conf
      echo  "hv_ata_pci_disengage_load=\"YES\""  >> /boot/loader.conf

   else
      echo "===> File $test does not exists"
      echo " Adding File $test and Hyper-v BIS driver labels"
      #Hyper-v driver names
      echo  "# Loader labels for Hyper-v BIS drivers -do not modify" >> /boot/loader.conf
      echo  "hv_vmbus_load=\"YES\"" >> /boot/loader.conf
      echo  "hv_utils_load=\"YES\""  >> /boot/loader.conf
      echo  "hv_storvsc_load=\"YES\""  >> /boot/loader.conf
      echo  "hv_netvsc_load=\"YES\""  >> /boot/loader.conf
      echo  "hv_ata_pci_disengage_load=\"YES\""  >> /boot/loader.conf
   fi

# KVP - daemon label
echo "===> Adding kvp daemon label" 
if [ -f "/etc/rc.conf" ]; then
   sed -i".bak" '/Labels for KVP daemon/d' /etc/rc.conf
   sed -i".bak" '/hv_kvp_daemon_enable/d' /etc/rc.conf
   echo  "# Labels for KVP daemon -do not modify" >> /etc/rc.conf
   echo  "hv_kvp_daemon_enable=\"YES\"" >> /etc/rc.conf
else
   echo  "# Labels for KVP daemon -do not modify" >> /etc/rc.conf
   echo  "hv_kvp_daemon_enable=\"YES\"" >> /etc/rc.conf
fi
fi
fi
exit 0
